function abreSite() {
    
    var arraySite = [
                    "http://burymewithmymoney.com/",
                    "http://eelslap.com/",
                    "http://www.staggeringbeauty.com/",
                    "http://www.movenowthinklater.com/",
                    "http://www.republiquedesmangues.fr/",
                    "http://www.sanger.dk/",
                    "http://www.partridgegetslucky.com/",
                    "http://theinternetfireplace.com/",
                    "http://gifctrl.com/",
                    "http://www.pointerpointer.com/",
                    "http://www.koalastothemax.com/",
                    "http://cachemonet.com/",
                    "http://baconsizzling.com/",
                    "http://iloveyoulikeafatladylovesapples.com/",
                    "http://heyyeyaaeyaaaeyaeyaa.com/",
                    "http://imgur-roulette.com/",
                    "http://davidbowieisverydisappointedinyou.com/",
                    "http://instantrimshot.com/classic/?sound=rimshot",
                    "http://www.findtheinvisiblecow.com/",
                    "http://brasilalemanhaeterno.com/",
                    "http://pudim.com.br/",
                    "http://davedonut.deviantart.com/art/Banner-WEbsite-v03-412695674",
                    "http://static.maniadescraps.com/imagens/cybergan38/animacoes/tetka.swf",
                    "http://ducksarethebest.com/",
                    "http://www.koalastothemax.com/",
                    "http://estipaper.com/",
                    "http://iacopoapps.appspot.com/hopalongwebgl/",
                    "http://csh.bz/gifmelter/melt.html",
                    "http://www.omfgdogs.com/",
                    "http://www.nyan.cat/",
                    "http://www.howmanypeopleareinspacerightnow.com/",
                    "http://geektyper.com/",
                    "http://jamesoff.net/fun/random-recipe-generator/",
                    "http://myprogressbar.com/",
                    "http://whatcolourisit.scn9a.org/",
                    "http://comicsans.de/",
                    "http://thisissand.com/",
                    "http://www.lalalalalalalalalalalalalalalalalala.com/",
                    "http://www.ismycomputeron.com/",
                    "http://www.muchbetterthanthis.com/",
                    "https://www.calm.com/",
                    "http://trololololololololololo.com/",
                    "http://www.naofuncionou.com/",
                    "http://emergencycompliment.com/",
                    "http://ventiladoronline.com/",
                    "http://www.thepointless.com/limerick-from-dimerick",
                    "http://www.donothingfor2minutes.com/",
                    "http://www.republiquedesmangues.fr/",
                    "http://isnickelbacktheworstbandever.tumblr.com/",
                    "http://www.rainymood.com/",
                    "http://www.clarifyscience.info/assets/day_of_dots_clock",
                    "http://make-everything-ok.com/",
                    "http://dandandan.net/",
                    "http://cat-bounce.com/",
                    "http://www.ringingtelephone.com/",
                    "http://beesbeesbees.com/",
                    "http://www.riddlydiddly.com/",
                    "http://www.nullingthevoid.com/",
                    "http://existentialcrisis.net/",
                    "http://leglesslegolegolas.com/",
                    "http://randomcolour.com/",
                    "http://www.clicktoremove.com/",
                    "http://www.winkyface.org/",
                    "http://giantbatfarts.com/",
                    "http://makeacelebrityodd.com/",
                    "http://grandpanoclothes.com/",
                    "http://www.jellotime.com/",
                    "http://www.davidbessler.com/pulldown/pipecleaner_dance3.swf",
                    "http://salmonofcapistrano.com/",
                    "http://www.vatican.va/various/cappelle/sistina_vr/",
                    "http://www.raaa.com.br/",
                    "http://www.zombo.com/",
                    "http://www.wutdafuk.com/",
                    "http://www.rrrgggbbb.com/",
                    "http://worlds-highest-website.com/",
                    "http://colinsgiraffe.com/",
                    "http://www.lalalaa.com/",
                    "http://www.ooooiiii.com/",
                    "http://heeeeeeeey.com/"
                    ];

    var randomSite = Math.floor(Math.random() * arraySite.length);
    window.open(arraySite[randomSite], '_blank');

    var click = 0
    click++;
    document.getElementById('p1').innerHTML = click + " " + "Coisas inúteis já exibidas";  
} 
